language: node_js
 
deploy:
  - provider: script
    script: echo "//registry.npmjs.org/:_authToken=$TOKEN" > ~/.npmrc 2>/dev/null
    on:
      tags: true
 
  - provider: script
    script: npm publish --access public
    on:
      tags: true
